exp:
  exp_name: direct
  context_path: outputs/ragtime/{exp_name}/context.run
  response_path: outputs/ragtime/{exp_name}/response.jsonl

data:
  queries_path: data/ragtime/queries_unified.jsonl
  corpus_path: data/ragtime/corpus/corpus.jsonl
  nugget_qrels_path: data/ragtime/qrels

selector:
  topk: null

generator:
  model_name_or_path: google/gemma-3-27b-it
  mode: vllm
  base_url: http://localhost:8000/v1
  api_key: EMPTY
  track: ragtime
  temperature: 0.0
  top_p: 1.0
  max_tokens: 1024
  max_model_len: 51200
