exp:
  exp_name: test
  context_path: outputs/biogen/{exp_name}/context.run
  response_path: outputs/biogen/{exp_name}/response.jsonl

data:
  queries_path: data/biogen/topics/queries_unified.jsonl
  corpus_path: data/biogen/corpus/corpus.jsonl
  run_path: data/biogen/runs/run.txt

retriever:
  topk: 100

selector:
  topk: 5

generator:
  model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
  track: biogen
  temperature: 0.0
  top_p: 1.0
  max_tokens: 512
  dtype: bfloat16
  gpu_memory_utilization: 0.9
  num_gpus: 1
  max_model_len: 10240
