exp:
  exp_name: test
  context_path: outputs/rag2024/{exp_name}/context.run
  response_path: outputs/rag2024/{exp_name}/response.jsonl

data:
  queries_path: data/rag2024/topics/queries_unified.jsonl
  corpus_path: data/rag2024/corpus/corpus.jsonl
  run_path: data/rag2024/runs/run.txt

retriever:
  topk: 100

selector:
  topk: 5

generator:
  model_name_or_path: google/gemma-3-27b-it
  track: rag
  temperature: 0.0
  top_p: 1.0
  max_tokens: 512
  dtype: bfloat16
  gpu_memory_utilization: 0.9
  max_model_len: 51200
