exp:
  exp_name: cover-top20
  context_path: outputs/ragtime/{exp_name}/context.run
  response_path: outputs/ragtime/{exp_name}/response.jsonl

data:
  corpus_path: data/ragtime/ragtime25-relevant-docs.jsonl
  nugget_qrels_path: data/ragtime/2025.mlir.qrels
  queries_path: data/ragtime2025.topics.test.jsonl
  run_path: runs/runs.ragtime2025.cover.test.txt

retriever:
  topk: 100

selector:
  topk: 20

generator:
  api_key: EMPTY
  base_url: http://localhost:8000/v1
  max_model_len: 51200
  max_tokens: 1024
  mode: vllm
  model_name_or_path: google/gemma-3-27b-it
  temperature: 0.0
  top_p: 1.0
  track: ragtime
