exp:
  exp_name: oracle-top50
  context_path: outputs/neuclir/{exp_name}/context.run
  response_path: outputs/neuclir/{exp_name}/response.jsonl

data:
  queries_path: data/neuclir2024.topics.test.jsonl
  corpus_path: data/neuclir/neuclir24-relevant-docs.jsonl
  nugget_qrels_path: data/neuclir/neuclir24-test-request.qrel

retriever:
  topk: 100

reranker:
  method: lancer

selector:
  topk: 50

generator:
  model_name_or_path: google/gemma-3-27b-it
  mode: vllm
  base_url: http://localhost:8000/v1
  api_key: EMPTY
  track: neuclir
  temperature: 0.0
  top_p: 1.0
  max_tokens: 1024
  max_model_len: 51200
